### ISSUE TITLE
Android: leftWindow does not respond to click events

### ISSUE THREAD

**Issue by ssenior45** [FokkeZB/nl.fokkezb.drawer#9]
Great work on this widget Fokke, many thanks for writing it.

I'm testing this out and have it working perfectly on iOS, but on Android the leftWindow does not respond to any click events.

Can you reproduce or am I doing something stupid?

**index.xml**

``` xml
<Alloy>
    <Widget id="drawer" src="nl.fokkezb.drawer">

        <Window module="xp.ui" role="leftWindow" id="menuWindow">
            <Button onClick="test">Left</Button>
            <TableView id="menuTable">

                <TableViewRow id="row" onClick="test">
                </TableViewRow>

            </TableView>
        </Window>

        <NavigationWindow platform="ios" role="centerWindow">
            <Window>
                <LeftNavButton>
                    <Button onClick="toggle">Left</Button>
                </LeftNavButton>
                <Label>I am center</Label>
                <!--
                <RightNavButton>
                    <Button onClick="toggle">Right</Button>
                </RightNavButton>
                -->
            </Window>
        </NavigationWindow>

        <View platform="android" role="centerWindow">
            <Label>I am center</Label>
        </View>
        <!--
        <Window module="xp.ui" role="rightWindow">
            <Label>I am right</Label>
        </Window>
        -->

    </Widget>
</Alloy>
```

**index.js**

``` javascript
function toggle(e) {
    var fn = 'toggle' + e.source.title + 'Window';
    $.drawer[fn]();
}

function test(e) {
    Ti.API.info('test clicked');
}

var data = []

var icon = $.UI.create('Label', { classes: ["appNewsIcon"] });
var text = $.UI.create('Label', { text: "App News", classes: ["menuLabel"] });
$.row.add(icon);
$.row.add(text);
data.push($.row)

$.menuTable.setData(data);

$.menuTable.addEventListener("click", function(e){
    Ti.API.info("isAnyWindowOpen: " + $.drawer.isAnyWindowOpen());
    switch(e.index){
        case 0:
            $.drawer.toggleLeftWindow(); //animate back to center
            alert("You clicked " + e.rowData.getChildren()[1].text + ". Implement menu structure.. ");
            break;
        case 1:
            $.drawer.setCenterWindow(Ti.UI.createView({backgroundColor:"red"}));
            $.drawer.toggleLeftWindow(); //animate back to center
            break;
    }
});

$.drawer.open();
```

**index.tss**

``` css
".container": {
    backgroundColor:"white"
},

"#drawer": {
    openDrawerGestureMode: "OPEN_MODE_ALL",
    closeDrawerGestureMode: "CLOSE_MODE_ALL",
    leftDrawerWidth: 200
}
"Window": {
    backgroundColor: 'white'
}

"#menuWindow": {
    fullscreen: true
}

//Menu items
".appNewsIcon": {
    left: 2,
    top: Alloy.Globals.top,//2,
    height: 30,
    width: 28,
    //backgroundColor: 'blue',
    font: { fontFamily: 'FontAwesome', fontSize:26 },
    color: '#0F0',
    shadowColor: '#aaa',
    shadowOffset: {x:-2, y:2},
    shadowRadius: 2,
    text: Alloy.Globals.fa.ticket
}

".menuLabel": {
    left: 30,
    top: Alloy.Globals.top,//2,
    height: 30,
    width: 170,
    color: '#576996',
    font: {fontSize:16, fontWeight:'bold', fontFamily:'Arial'},
    textAlign: Ti.UI.TEXT_ALIGNMENT_LEFT
    //backgroundColor: 'red'
}
```

**tinfo**

``` bash
Titanium Command-Line Interface, CLI version 3.2.1, Titanium SDK version 3.2.1.GA
Copyright (c) 2012-2014, Appcelerator, Inc.  All Rights Reserved.

Please report bugs to http://jira.appcelerator.org/

Operating System
  Name                        = Mac OS X
  Version                     = 10.8.5
  Architecture                = 64bit
  # CPUs                      = 4
  Memory                      = 4.0GB

Node.js
  Node.js Version             = 0.10.13
  npm Version                 = 1.3.2

Titanium CLI
  CLI Version                 = 3.2.1
  node-appc Version           = 0.2.0

Titanium SDKs
  3.2.1.GA
    Install Location          = /Library/Application Support/Titanium/mobilesdk/osx/3.2.1.GA
    Platforms                 = iphone, tizen, mobileweb, android, blackberry
    git Hash                  = 991027b
    git Timestamp             = 02/06/14 17:01
    node-appc Version         = 0.2.0
  3.2.0.GA
    Install Location          = /Library/Application Support/Titanium/mobilesdk/osx/3.2.0.GA
    Platforms                 = iphone, tizen, mobileweb, android, blackberry
    git Hash                  = d9182d6
    git Timestamp             = 12/20/13 10:56
    node-appc Version         = 0.2.0
```

**dk.napp.drawer versions**

``` bash
Steven-Seniors-iMac:modules stevensenior$ pwd
/Users/stevensenior/Library/Application Support/Titanium/modules
Steven-Seniors-iMac:modules stevensenior$ ls -l */*
android/dk.napp.drawer:
total 0
drwxr-xr-x  10 stevensenior  staff  340 14 Feb 21:32 1.1.1

iphone/dk.napp.drawer:
total 0
drwxr-xr-x  7 stevensenior  staff  238 14 Feb 21:32 1.1.4
```

Many thanks in advance for looking.

Steve
